name: 🚀 Deploy Vayla Website

on:
  push:
    branches:
      - feat/refactor-nextjs # Tự động chạy khi push vào branch này

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: 📦 Install dependencies
        run: npm install

      - name: 🔨 Build Project
        run: |
          npm install
          npm run build
        env:
          NEXT_PUBLIC_BASE_URL: https://vayla.io

      - name: 📂 Sync files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./out/ # Thư mục sinh ra sau khi build export
          server-dir: ./public_html/ # Thư mục chứa web trên hosting của bạn
